n = str(input('Digite seu nome completo: ')).strip()
nome = n.split()
print('\033[46m Muito prazer \033[m em te conhecer!')
print('Seu primeiro nome é {}'.format(nome[0]))
print('Seu ultimo nome é {}'.format(nome[len(nome)-1]))
